#!/bin/python

import urllib.request, json

city = "Nancy"
api_key = "531565a2b4f28b8eb5a3ce26040f5428"
units = "Metric"
unit_key = "C"

weather = eval(str(urllib.request.urlopen("http://api.openweathermap.org/data/2.5/weather?q={}&APPID={}&units={}".format(city, api_key, units)).read())[2:-1])

info = weather["weather"][0]["description"].capitalize()
temp = int(float(weather["main"]["temp"]))

print("%s: %s, %i °%s" % (city, info, temp, unit_key))
